name: scribblr
description: "Article & Blog App."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  nb_utils: ^6.1.2
  google_fonts: ^6.1.0
  country_picker: ^2.0.24
  flag: ^7.0.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0
  ionicons: ^0.2.2
  image_picker: ^1.0.7
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2
  shared_preferences: ^2.2.2



  provider: any
dev_dependencies:
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/icons/
   - assets/lottie/
   - assets/authors/
   - assets/articles/
   - assets/icon.png